[solarflow]
# This transport layer supports Solarflow Hub 2000 only.
# Hub 2000 product_id = "A8yh63"
#product_id = A8yh63
# The device ID of your Solarflow Hub 2000 (typically 8 characters), you can get it either with solarflow-bt-manager or the solarflow-statuspage
device_id = 5ak8yGU7
[ace]
# The product ID of your ACE 1500 unit
#product_id =
# The device ID of your ACE 1500 unit
#device_id =

[mqtt]
# Your local MQTT host configuration
mqtt_host = 192.168.1.245
#mqtt_port = 
#mqtt_user =
#mqtt_pwd =